# Generated by Django 4.2.6 on 2023-11-11 06:37

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Criminal_Firstname', models.CharField(default='', max_length=100)),
                ('Criminal_Middlename', models.CharField(default='', max_length=5)),
                ('Criminal_Lastname', models.CharField(default='', max_length=100)),
                ('Criminal_Description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CriminalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Criminal_Image', models.ImageField(upload_to=app.models.criminal_image_upload_to)),
                ('Criminal', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.criminal')),
            ],
        ),
    ]
